FROM oven/bun:1 as base

WORKDIR /usr/src/app

FROM base as install

run mkdir -p /temp/dev

COPY package*.json bun.lockb /temp/dev/

RUN cd /temp/dev && bun install --frozen-lockfile

RUN bun install

COPY . .

RUN bun run build

EXPOSE 3000

CMD ["bun", "run", "start"]